info:
  prefix: 'puppet-module'
  authors: 'Puppet, Inc.'
  email: 'puppet-module-gems-maintainers@puppet.com'
  homepage: 'https://github.com/puppetlabs/puppet-module-gems'
  licenses: 'Apache-2.0'
  summary: 'A set of gems declaring Puppet module dependencies.'
  version: '1.1.1'
